import { REHYDRATE as REHYDRATE_ACTION } from 'redux-persist/constants';
export const REHYDRATE = REHYDRATE_ACTION;

// ui
export const SHOW_NOTIFICATON = 'SHOW_NOTIFICATON';
export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_FRAME = 'SHOW_FRAME';
export const ON_SEARCH_QUERY = 'ON_SEARCH_QUERY';
export const ON_SEARCH_START = 'ON_SEARCH_START';
export const ON_SEARCH_RESULT = 'ON_SEARCH_RESULT';
export const ADD_PACKAGE = 'ADD_PACKAGE';
export const ADD_PLATFORM = 'ADD_PLATFORM';
export const REMOVE_PLATFORM = 'REMOVE_PLATFORM';
export const UPDATE_PLATFORM = 'UPDATE_PLATFORM';
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';